parameters:
#    wini_token.example.class: Wini\TokenBundle\Example

services:
#    wini_token.example:
#        class: %wini_token.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    wini.token.manager:
        class: Wini\TokenBundle\Manager\TokenManager
        arguments: [ "@doctrine.orm.entity_manager" ]